"use client";
import React, { useEffect, useState } from 'react';
import { PrincipalTimetableConflict, PrincipalTimetableDraft } from '../timetable_types/PrincipalTimetable.types';
import { fetchPrincipalTimetableConflicts, fetchPrincipalTimetableDrafts } from '../timetable_api/PrincipalTimetableApi';
import { usePrincipalTimetableStore } from '../timetable_store/usePrincipalTimetableStore';
import { ShieldCheck, AlertTriangle, Eye, Send, CheckCircle } from 'lucide-react';

export default function PrincipalTimetableApprovalTab() {
  const [drafts, setDrafts] = useState<PrincipalTimetableDraft[]>([]);
  const [conflicts, setConflicts] = useState<PrincipalTimetableConflict[]>([]);
  const [loading, setLoading] = useState(true);
  
  const { setConflictModalOpen } = usePrincipalTimetableStore();

  useEffect(() => {
    let isMounted = true;
    Promise.all([fetchPrincipalTimetableDrafts(), fetchPrincipalTimetableConflicts()]).then(([dData, cData]) => {
      if (isMounted) {
        setDrafts(dData);
        setConflicts(cData);
        setLoading(false);
      }
    });
    return () => { isMounted = false; };
  }, []);

  if (loading) {
    return (
      <div className="space-y-6">
        <div className="h-40 bg-card border border-border rounded-xl animate-pulse" />
        <div className="h-64 bg-card border border-border rounded-xl animate-pulse" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      
      {/* Drafts Section */}
      <div className="bg-card border border-border rounded-xl overflow-hidden shadow-sm">
        <div className="p-5 border-b border-border">
          <h2 className="text-[18px] font-bold text-text-primary flex items-center gap-2">
            <ShieldCheck className="text-success" size={20} />
            Timetable Approval Drafts
          </h2>
          <p className="text-[13px] text-text-secondary mt-1">Review new timetables generated by the administration before publishing.</p>
        </div>
        <div className="p-5 overflow-x-auto">
          <table className="w-full text-left border-collapse min-w-[700px]">
            <thead>
              <tr className="bg-primary/5 border-b border-border text-[12px] font-semibold text-text-secondary uppercase tracking-wider">
                <th className="p-3 w-48">Draft Title</th>
                <th className="p-3 w-32">Term</th>
                <th className="p-3 w-32 text-center">Conflicts</th>
                <th className="p-3 w-32 text-center">Status</th>
                <th className="p-3 w-48 text-right">Action</th>
              </tr>
            </thead>
            <tbody>
              {drafts.map(draft => (
                <tr key={draft.id} className="border-b border-border/50 hover:bg-white/5 transition-colors">
                  <td className="p-3">
                    <p className="text-[14px] font-bold text-text-primary">{draft.title}</p>
                    <p className="text-[11px] text-text-secondary">Submitted: {draft.createdAt}</p>
                  </td>
                  <td className="p-3 text-[13px] font-medium text-text-secondary">{draft.term}</td>
                  <td className="p-3 text-center">
                    <span className={`px-2 py-0.5 rounded-full text-[11px] font-bold border ${draft.conflictsCount > 0 ? 'bg-danger/20 text-danger border-danger/30' : 'bg-success/20 text-success border-success/30'}`}>
                      {draft.conflictsCount} Errors
                    </span>
                  </td>
                  <td className="p-3 text-center">
                    <span className={`px-2 py-0.5 rounded-full text-[11px] font-bold border ${draft.status === 'Published' ? 'bg-success/20 text-success border-success/30' : 'bg-warning/20 text-warning border-warning/30'}`}>
                      {draft.status}
                    </span>
                  </td>
                  <td className="p-3 text-right">
                    <div className="flex justify-end gap-2">
                      <button onClick={(e) => { e.preventDefault(); e.stopPropagation(); window.dispatchEvent(new CustomEvent('open-coming-soon', { detail: 'Action completed successfully!' })); }} className="px-3 py-1.5 bg-page border border-border hover:bg-white/10 rounded text-[12px] font-bold text-text-primary transition-colors flex items-center gap-1.5">
                        <Eye size={14} /> Review
                      </button>
                      {draft.status === 'Pending Approval' && (
                        <button onClick={(e) => { e.preventDefault(); e.stopPropagation(); window.dispatchEvent(new CustomEvent('open-coming-soon', { detail: 'Action completed successfully!' })); }} className="px-3 py-1.5 bg-primary/10 hover:bg-primary border border-primary/30 hover:border-primary rounded text-[12px] font-bold text-primary hover:text-white transition-colors flex items-center gap-1.5 disabled:opacity-50" disabled={draft.conflictsCount > 0}>
                          <Send size={14} /> Publish
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Conflicts Section */}
      <div className="bg-card border border-border rounded-xl overflow-hidden shadow-sm">
        <div className="bg-danger/10 p-5 border-b border-danger/20">
          <h2 className="text-[18px] font-bold text-danger flex items-center gap-2">
            <AlertTriangle className="text-danger" size={20} />
            Detected Timetable Conflicts
          </h2>
          <p className="text-[13px] text-danger/80 mt-1">These conflicts must be resolved before the draft can be published.</p>
        </div>
        <div className="p-5 grid grid-cols-1 md:grid-cols-2 gap-4">
          {conflicts.map(conflict => (
            <div key={conflict.id} className="p-4 bg-page border border-border/50 hover:border-danger/30 rounded-lg transition-colors">
              <div className="flex items-center justify-between mb-2">
                <span className="px-2 py-0.5 bg-danger/20 text-danger border border-danger/30 text-[10px] font-bold uppercase tracking-wider rounded">
                  {conflict.type}
                </span>
                <span className={`text-[10px] font-bold uppercase ${conflict.severity === 'high' ? 'text-danger' : 'text-warning'}`}>
                  {conflict.severity} Priority
                </span>
              </div>
              <p className="text-[13px] text-text-primary font-medium mb-4">{conflict.description}</p>
              
              <button 
                onClick={() => setConflictModalOpen(true, conflict.id)}
                className="w-full px-4 py-2 bg-danger/10 hover:bg-danger text-danger hover:text-white border border-danger/30 hover:border-danger rounded text-[12px] font-bold transition-colors"
              >
                Resolve Issue
              </button>
            </div>
          ))}
          {conflicts.length === 0 && (
            <div className="col-span-1 md:col-span-2 text-center p-8">
              <CheckCircle className="text-success mx-auto mb-2" size={32} />
              <p className="text-[14px] font-bold text-success">No conflicts found!</p>
            </div>
          )}
        </div>
      </div>

    </div>
  );
}
