import type { TransportVehicle } from '../transport_vehicles_types/transport_vehicles.types';

export const MOCK_TRANSPORT_VEHICLES: TransportVehicle[] = [
  {
    id: 'VEH-001',
    vehicleNumber: 'MH-12-AB-1234',
    registrationNumber: 'REG-987654321',
    vehicleType: 'BUS',
    seatingCapacity: 45,
    model: 'Tata Marcopolo',
    manufacturer: 'Tata Motors',
    purchaseDate: '2020-05-15',
    fuelType: 'DIESEL',
    status: 'ACTIVE',
    assignedRouteId: 'RT-01',
    assignedRouteName: 'Route A - City Center',
    assignedDriverId: 'DRV-101',
    assignedDriverName: 'Rajesh Kumar',
    assignedConductorId: 'CND-201',
    assignedConductorName: 'Sanjay Verma',
    gpsDeviceId: 'GPS-8899',
    documentsComplete: true,
  },
  {
    id: 'VEH-002',
    vehicleNumber: 'MH-12-CD-5678',
    registrationNumber: 'REG-123456789',
    vehicleType: 'BUS',
    seatingCapacity: 50,
    model: 'Ashok Leyland Falcon',
    manufacturer: 'Ashok Leyland',
    purchaseDate: '2021-02-10',
    fuelType: 'CNG',
    status: 'MAINTENANCE',
    assignedRouteId: 'RT-02',
    assignedRouteName: 'Route B - North Campus',
    assignedDriverId: 'DRV-102',
    assignedDriverName: 'Suresh Patil',
    assignedConductorId: 'CND-202',
    assignedConductorName: 'Anil Desai',
    gpsDeviceId: 'GPS-7766',
    documentsComplete: false,
  },
  {
    id: 'VEH-003',
    vehicleNumber: 'MH-12-EF-9012',
    registrationNumber: 'REG-456123789',
    vehicleType: 'VAN',
    seatingCapacity: 15,
    model: 'Force Traveller',
    manufacturer: 'Force Motors',
    purchaseDate: '2022-08-20',
    fuelType: 'DIESEL',
    status: 'RESTRICTED',
    assignedRouteId: null,
    assignedRouteName: null,
    assignedDriverId: null,
    assignedDriverName: null,
    assignedConductorId: null,
    assignedConductorName: null,
    gpsDeviceId: null,
    documentsComplete: true,
  }
];

export const VEHICLE_STATUS_COLORS: Record<string, { bg: string, text: string, label: string }> = {
  ACTIVE: { bg: '#064E3B', text: '#22C55E', label: 'Active' },
  INACTIVE: { bg: '#1E1E2E', text: 'var(--text-secondary)', label: 'Inactive' },
  MAINTENANCE: { bg: '#451A03', text: '#F59E0B', label: 'Maintenance' },
  RESTRICTED: { bg: '#450A0A', text: '#EF4444', label: 'Restricted' },
  RETIRED: { bg: '#1E1E2E', text: 'var(--text-secondary)', label: 'Retired' },
};
