import type { SchoolRoleId, ModuleId } from '../../(app)/super-admin/02-organization-management/organization_management_types/super_admin_school_config.types';

export const DEMO_SCHOOLS = [
  {
    id: 'school-a-small',
    name: 'Demo Small School',
    size: 'small',
    roles: {
      'school-admin': true,
      'principal': false,
      'teacher': false,
      'accountant': false,
      'hr': false,
      'student': false,
      'parent': false,
      'librarian': false,
      'transport-manager': false,
      'hostel-warden': false,
    },
    modules: {},
  },
  {
    id: 'school-b-medium',
    name: 'Demo Medium School',
    size: 'medium',
    roles: {
      'school-admin': true,
      'principal': true,
      'teacher': true,
      'accountant': true,
      'hr': false,
      'student': false,
      'parent': false,
      'librarian': false,
      'transport-manager': false,
      'hostel-warden': false,
    },
    modules: {},
  },
  {
    id: 'school-c-large',
    name: 'Demo Large School',
    size: 'large',
    roles: {
      'school-admin': true,
      'principal': true,
      'teacher': true,
      'accountant': true,
      'hr': true,
      'student': true,
      'parent': true,
      'librarian': false,
      'transport-manager': false,
      'hostel-warden': false,
    },
    modules: {
      'library': false,
      'transport': false,
      'hostel': false,
    },
  },
  {
    id: 'school-d-lib',
    name: 'Demo Large (Library Enabled)',
    size: 'large',
    roles: {
      'school-admin': true,
      'principal': true,
      'teacher': true,
      'accountant': true,
      'hr': true,
      'student': true,
      'parent': true,
      'librarian': true,
      'transport-manager': false,
      'hostel-warden': false,
    },
    modules: {
      'library': true,
      'transport': false,
      'hostel': false,
    },
  },
  {
    id: 'school-e-trans',
    name: 'Demo Large (Transport Enabled)',
    size: 'large',
    roles: {
      'school-admin': true,
      'principal': true,
      'teacher': true,
      'accountant': true,
      'hr': true,
      'student': true,
      'parent': true,
      'librarian': false,
      'transport-manager': true,
      'hostel-warden': false,
    },
    modules: {
      'library': false,
      'transport': true,
      'hostel': false,
    },
  },
  {
    id: 'school-f-hostel',
    name: 'Demo Large (Hostel Enabled)',
    size: 'large',
    roles: {
      'school-admin': true,
      'principal': true,
      'teacher': true,
      'accountant': true,
      'hr': true,
      'student': true,
      'parent': true,
      'librarian': false,
      'transport-manager': false,
      'hostel-warden': true,
    },
    modules: {
      'library': false,
      'transport': false,
      'hostel': true,
    },
  },
];
