import { Shield, School, GraduationCap, Calculator, Users, UserCircle, BookOpen, Bus, Key, Building2 } from 'lucide-react';
import type { SchoolRoleId, ModuleId } from '../(app)/super-admin/02-organization-management/organization_management_types/super_admin_school_config.types';

export const DEMO_SCHOOLS = [
  {
    id: 'school-a-small',
    name: 'Demo Small School',
    size: 'small',
    roles: {
      'school-admin': true,
      'principal': false,
      'teacher': false,
      'accountant': false,
      'hr': false,
      'student': false,
      'parent': false,
      'librarian': false,
      'transport-manager': false,
      'hostel-warden': false,
    },
    modules: {},
  },
  {
    id: 'school-b-medium',
    name: 'Demo Medium School',
    size: 'medium',
    roles: {
      'school-admin': true,
      'principal': true,
      'teacher': true,
      'accountant': true,
      'hr': false,
      'student': false,
      'parent': false,
      'librarian': false,
      'transport-manager': false,
      'hostel-warden': false,
    },
    modules: {},
  },
  {
    id: 'school-c-large',
    name: 'Demo Large School',
    size: 'large',
    roles: {
      'school-admin': true,
      'principal': true,
      'teacher': true,
      'accountant': true,
      'hr': true,
      'student': true,
      'parent': true,
      'librarian': false,
      'transport-manager': false,
      'hostel-warden': false,
    },
    modules: {
      'library': false,
      'transport': false,
      'hostel': false,
    },
  },
  {
    id: 'school-d-lib',
    name: 'Demo Large (Library Enabled)',
    size: 'large',
    roles: {
      'school-admin': true,
      'principal': true,
      'teacher': true,
      'accountant': true,
      'hr': true,
      'student': true,
      'parent': true,
      'librarian': true,
      'transport-manager': false,
      'hostel-warden': false,
    },
    modules: {
      'library': true,
      'transport': false,
      'hostel': false,
    },
  },
  {
    id: 'school-e-trans',
    name: 'Demo Large (Transport Enabled)',
    size: 'large',
    roles: {
      'school-admin': true,
      'principal': true,
      'teacher': true,
      'accountant': true,
      'hr': true,
      'student': true,
      'parent': true,
      'librarian': false,
      'transport-manager': true,
      'hostel-warden': false,
    },
    modules: {
      'library': false,
      'transport': true,
      'hostel': false,
    },
  },
  {
    id: 'school-f-hostel',
    name: 'Demo Large (Hostel Enabled)',
    size: 'large',
    roles: {
      'school-admin': true,
      'principal': true,
      'teacher': true,
      'accountant': true,
      'hr': true,
      'student': true,
      'parent': true,
      'librarian': false,
      'transport-manager': false,
      'hostel-warden': true,
    },
    modules: {
      'library': false,
      'transport': false,
      'hostel': true,
    },
  },
];

export const ROLE_LOGIN_CONFIG: Record<string, any> = {
  'school-admin': {
    id: 'school-admin',
    label: 'School Admin',
    description: 'School Management & Operations',
    icon: School,
    color: '#0F766E', // Primary
    bgColor: '#0F766E0D', // Light bg (5-10%)
    route: '/login/school-admin',
    dashboardRoute: '/school-admin/dashboard',
    demoUser: 'admin',
    demoPass: 'admin123'
  },
  'principal': {
    id: 'principal',
    label: 'Principal',
    description: 'Executive Overview & Dashboards',
    icon: Building2,
    color: '#7C3AED',
    bgColor: '#7C3AED0D',
    route: '/login/principal',
    dashboardRoute: '/principal/dashboard',
    demoUser: 'principal',
    demoPass: 'principal123'
  },
  'teacher': {
    id: 'teacher',
    label: 'Teacher',
    description: 'Classes, Grades & Students',
    icon: GraduationCap,
    color: '#15803D',
    bgColor: '#15803D0D',
    route: '/login/teacher',
    dashboardRoute: '/teacher/dashboard',
    demoUser: 'teacher',
    demoPass: 'teacher123'
  },
  'accountant': {
    id: 'accountant',
    label: 'Accountant',
    description: 'Finance, Fees & Expense Tracking',
    icon: Calculator,
    color: '#475569',
    bgColor: '#4755690D',
    route: '/login/accountant',
    dashboardRoute: '/accountant/dashboard',
    demoUser: 'accountant',
    demoPass: 'accountant123'
  },
  'hr': {
    id: 'hr',
    label: 'HR / Office',
    description: 'Staff, Payroll & HR Operations',
    icon: Users,
    color: '#BE185D',
    bgColor: '#BE185D0D',
    route: '/login/hr',
    dashboardRoute: '/hr/dashboard',
    demoUser: 'hr',
    demoPass: 'hr123'
  },
  'student': {
    id: 'student',
    label: 'Student',
    description: 'Academics, Timetable & Exams',
    icon: UserCircle,
    color: '#0284C7',
    bgColor: '#0284C70D',
    route: '/login/student',
    dashboardRoute: '/student/dashboard',
    demoUser: 'student',
    demoPass: 'student123'
  },
  'parent': {
    id: 'parent',
    label: 'Parent / Guardian',
    description: 'Fees, Attendance & Progress',
    icon: Users,
    color: '#B45309',
    bgColor: '#B453090D',
    route: '/login/parent',
    dashboardRoute: '/parent/dashboard',
    demoUser: 'parent',
    demoPass: 'parent123'
  },
  'librarian': {
    id: 'librarian',
    label: 'Librarian',
    description: 'Books, Circulation & Records',
    icon: BookOpen,
    color: '#6D28D9',
    bgColor: '#6D28D90D',
    route: '/login/librarian',
    dashboardRoute: '/librarian/dashboard',
    demoUser: 'librarian',
    demoPass: 'librarian123'
  },
  'transport-manager': {
    id: 'transport-manager',
    label: 'Transport Manager',
    description: 'Vehicles, Routes & Tracking',
    icon: Bus,
    color: '#0891B2',
    bgColor: '#0891B20D',
    route: '/login/transport-manager',
    dashboardRoute: '/transport/dashboard',
    demoUser: 'transport',
    demoPass: 'transport123'
  },
  'hostel-warden': {
    id: 'hostel-warden',
    label: 'Hostel Warden',
    description: 'Hostels, Rooms & Allocations',
    icon: Key,
    color: '#166534',
    bgColor: '#1665340D',
    route: '/login/hostel-warden',
    dashboardRoute: '/hostel/dashboard',
    demoUser: 'hostel',
    demoPass: 'hostel123'
  }
};
