"use client";
import React from "react";
import { FileText, Download, Loader2, AlertCircle, Eye } from "lucide-react";
import { useHRReportsStore } from "../hr_reports_store/useHRReportsStore";
import clsx from "clsx";

export default function HRReportsTable() {
  const { reportsData, searchQuery, categoryFilter, statusFilter, setActionModalOpen, setSelectedRecord } = useHRReportsStore();

  const filteredData = reportsData.filter(record => {
    const matchesSearch = record.reportName.toLowerCase().includes(searchQuery.toLowerCase());
    
    const matchesCategory = categoryFilter === "All" || record.category === categoryFilter;
    const matchesStatus = statusFilter === "All" || record.status === statusFilter;
    
    return matchesSearch && matchesCategory && matchesStatus;
  });

  const getStatusColor = (status: string) => {
    switch(status) {
      case 'Ready': return 'text-emerald-700 bg-emerald-50 border-emerald-200';
      case 'Generating': return 'text-indigo-700 bg-indigo-50 border-indigo-200';
      case 'Failed': return 'text-rose-700 bg-rose-50 border-rose-200';
      default: return 'text-slate-700 bg-slate-50 border-slate-200';
    }
  };

  const handleAction = (record: any) => {
    if (record.status !== 'Ready') return;
    setSelectedRecord(record);
    setActionModalOpen(true);
  };

  return (
    <div className="bg-card border border-border rounded-2xl shadow-sm overflow-hidden">
      <div className="overflow-x-auto custom-scrollbar">
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="bg-bg-input border-b border-border">
              <th className="p-4 text-xs font-black text-text-secondary uppercase tracking-wider">Report Name & Details</th>
              <th className="p-4 text-xs font-black text-text-secondary uppercase tracking-wider hidden md:table-cell">Generated By</th>
              <th className="p-4 text-xs font-black text-text-secondary uppercase tracking-wider">Format</th>
              <th className="p-4 text-xs font-black text-text-secondary uppercase tracking-wider">Status</th>
              <th className="p-4 text-xs font-black text-text-secondary uppercase tracking-wider text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-border">
            {filteredData.map((record) => (
              <tr key={record.id} className="hover:bg-bg-page/50 transition-colors group">
                <td className="p-4">
                  <div className="flex items-start gap-3">
                    <div className="p-2 rounded-lg bg-purple-50 border border-purple-100 mt-1 shrink-0">
                      <FileText size={16} className="text-purple-500" />
                    </div>
                    <div>
                      <p className="text-sm font-bold text-text-primary group-hover:text-purple-600 transition-colors">{record.reportName}</p>
                      <p className="text-[11px] font-semibold text-text-secondary mt-0.5">{record.category} • {record.date}</p>
                    </div>
                  </div>
                </td>
                <td className="p-4 hidden md:table-cell">
                  <p className="text-sm font-bold text-text-primary">{record.generatedBy}</p>
                </td>
                <td className="p-4">
                  <span className="px-2 py-1 rounded text-[10px] font-bold bg-bg-page border border-border text-text-secondary">
                    {record.format}
                  </span>
                </td>
                <td className="p-4">
                  <span className={clsx("px-2.5 py-1 rounded-md text-[11px] font-bold border flex items-center gap-1.5 w-max", getStatusColor(record.status))}>
                    {record.status === 'Generating' && <Loader2 size={12} className="animate-spin" />}
                    {record.status === 'Failed' && <AlertCircle size={12} />}
                    {record.status}
                  </span>
                </td>
                <td className="p-4 text-right">
                  <div className="flex items-center justify-end gap-2">
                    {record.status === 'Ready' ? (
                      <button 
                        onClick={() => handleAction(record)}
                        className="px-3 py-1.5 text-xs font-bold text-purple-700 bg-purple-50 hover:bg-purple-100 rounded-lg transition-colors border border-purple-200 flex items-center gap-1.5"
                      >
                        <Download size={14} /> Download
                      </button>
                    ) : (
                      <button 
                        disabled
                        className="px-3 py-1.5 text-xs font-bold text-text-secondary/50 bg-bg-page rounded-lg border border-transparent cursor-not-allowed"
                      >
                        Not Available
                      </button>
                    )}
                  </div>
                </td>
              </tr>
            ))}
            {filteredData.length === 0 && (
              <tr>
                <td colSpan={5} className="p-8 text-center text-text-secondary font-semibold">
                  No reports found matching your criteria.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
